[package]
name = "donation_badge"
type = "bin"
authors = ["Tongo Donation Demo"]
compiler_version = "1.0.0-beta.1"

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }

